# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Code Formatter

on:
  pull_request:
    branches:
      - main

jobs:
  Formate:
    runs-on: macos-13
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Format code
        run: swiftformat --lint --swiftversion 5.5 .
     
