# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Code Formatter

on:
  pull_request:
    branches:
      - main

jobs:
  Formate:
    env:
      SWIFT_VERSION: '5.5'
    runs-on: macos-13
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Build
        run: cd bitMaker-sirius-ios
          xcodebuild build -project BeatMaker.xcodeproj -scheme BeatMaker clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

      - name: Lint code
        run: swiftformat --lint --swiftversion ${{env.SWIFT_VERSION}} .     
